name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: selft-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull nelsonnpl/nodejs-restapi:latest
    - name: Delete Old docker container
      run: sudo docker rm -f nodejs-restapi-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name nodejs-restapi-container nelsonnpl/nodejs-restapi